// Comprehensive rental inventory with detailed specs and pricing
export const rentalModels = [
  // Boom Lifts
  {
    id: 'jlg-340ax',
    category: 'boom-lifts',
    name: 'JLG 340AX',
    height: 40,
    reach: 35,
    capacity: 500,
    power: 'Diesel',
    width: 8.5,
    weight: 8200,
    dailyRate: 450,
    weeklyRate: 1200,
    monthlyRate: 3200,
    imageUrl: 'https://www.allaccessservices.com/site-assets/equipment/jlg-1200sjp-hero.jpg',
    specSheet: 'https://www.allaccessservices.com/resources/spec-sheets',
  },
  {
    id: 'jlg-400s',
    category: 'boom-lifts',
    name: 'JLG 400S',
    height: 40,
    reach: 35,
    capacity: 500,
    power: 'Diesel',
    width: 8.5,
    weight: 10500,
    dailyRate: 495,
    weeklyRate: 1350,
    monthlyRate: 3600,
    imageUrl: 'https://www.allaccessservices.com/site-assets/equipment/jlg-1200sjp-hero.jpg',
    specSheet: 'https://www.allaccessservices.com/resources/spec-sheets',
  },
  {
    id: 'jlg-600s',
    category: 'boom-lifts',
    name: 'JLG 600S',
    height: 60,
    reach: 52,
    capacity: 600,
    power: 'Diesel',
    width: 8.5,
    weight: 14200,
    dailyRate: 595,
    weeklyRate: 1650,
    monthlyRate: 4400,
    imageUrl: 'https://www.allaccessservices.com/site-assets/equipment/jlg-1200sjp-hero.jpg',
    specSheet: 'https://www.allaccessservices.com/resources/spec-sheets',
  },
  {
    id: 'jlg-800a',
    category: 'boom-lifts',
    name: 'JLG 800A',
    height: 80,
    reach: 67,
    capacity: 750,
    power: 'Diesel',
    width: 8.5,
    weight: 19200,
    dailyRate: 695,
    weeklyRate: 1950,
    monthlyRate: 5200,
    imageUrl: 'https://www.allaccessservices.com/site-assets/equipment/jlg-1200sjp-hero.jpg',
    specSheet: 'https://www.allaccessservices.com/resources/spec-sheets',
  },
  {
    id: 'jlg-1200sjp',
    category: 'boom-lifts',
    name: 'JLG 1200SJP',
    height: 120,
    reach: 100,
    capacity: 1000,
    power: 'Diesel',
    width: 8.5,
    weight: 28000,
    dailyRate: 895,
    weeklyRate: 2550,
    monthlyRate: 6800,
    imageUrl: 'https://www.allaccessservices.com/site-assets/equipment/jlg-1200sjp-hero.jpg',
    specSheet: 'https://www.allaccessservices.com/resources/spec-sheets',
  },

  // Scissor Lifts
  {
    id: 'jlg-1930m',
    category: 'scissor-lifts',
    name: 'JLG 1930M',
    height: 19,
    reach: 0,
    capacity: 500,
    power: 'Electric',
    width: 2.5,
    weight: 2200,
    dailyRate: 125,
    weeklyRate: 350,
    monthlyRate: 900,
    imageUrl: 'https://www.allaccessservices.com/site-assets/equipment/jlg-es1932.jpg',
    specSheet: 'https://www.allaccessservices.com/resources/spec-sheets',
  },
  {
    id: 'jlg-2030es',
    category: 'scissor-lifts',
    name: 'JLG 2030ES',
    height: 20,
    reach: 0,
    capacity: 500,
    power: 'Electric',
    width: 2.85,
    weight: 3900,
    dailyRate: 145,
    weeklyRate: 400,
    monthlyRate: 1050,
    imageUrl: 'https://www.allaccessservices.com/site-assets/equipment/jlg-es1932.jpg',
    specSheet: 'https://www.allaccessservices.com/resources/spec-sheets',
  },
  {
    id: 'jlg-3369le',
    category: 'scissor-lifts',
    name: 'JLG 3369LE',
    height: 33,
    reach: 0,
    capacity: 600,
    power: 'Diesel',
    width: 3.6,
    weight: 6500,
    dailyRate: 185,
    weeklyRate: 525,
    monthlyRate: 1400,
    imageUrl: 'https://www.allaccessservices.com/site-assets/equipment/jlg-es1932.jpg',
    specSheet: 'https://www.allaccessservices.com/resources/spec-sheets',
  },
  {
    id: 'jlg-4069le',
    category: 'scissor-lifts',
    name: 'JLG 4069LE',
    height: 40,
    reach: 0,
    capacity: 700,
    power: 'Diesel',
    width: 3.9,
    weight: 8200,
    dailyRate: 225,
    weeklyRate: 625,
    monthlyRate: 1650,
    imageUrl: 'https://www.allaccessservices.com/site-assets/equipment/jlg-es1932.jpg',
    specSheet: 'https://www.allaccessservices.com/resources/spec-sheets',
  },
  {
    id: 'jlg-6069rt',
    category: 'scissor-lifts',
    name: 'JLG 6069RT',
    height: 60,
    reach: 0,
    capacity: 1000,
    power: 'Diesel',
    width: 4.5,
    weight: 15600,
    dailyRate: 325,
    weeklyRate: 900,
    monthlyRate: 2400,
    imageUrl: 'https://www.allaccessservices.com/site-assets/equipment/jlg-es1932.jpg',
    specSheet: 'https://www.allaccessservices.com/resources/spec-sheets',
  },

  // Telehandlers
  {
    id: 'jlg-6000',
    category: 'telehandlers',
    name: 'JLG G6-54',
    height: 54,
    reach: 43,
    capacity: 6000,
    power: 'Diesel',
    width: 8,
    weight: 22000,
    dailyRate: 495,
    weeklyRate: 1350,
    monthlyRate: 3600,
    imageUrl: 'https://www.allaccessservices.com/site-assets/equipment/skytrak-10054.jpg',
    specSheet: 'https://www.allaccessservices.com/resources/spec-sheets',
  },
  {
    id: 'jlg-8000',
    category: 'telehandlers',
    name: 'JLG G8-55A',
    height: 55,
    reach: 43,
    capacity: 8000,
    power: 'Diesel',
    width: 8,
    weight: 26000,
    dailyRate: 595,
    weeklyRate: 1650,
    monthlyRate: 4400,
    imageUrl: 'https://www.allaccessservices.com/site-assets/equipment/skytrak-10054.jpg',
    specSheet: 'https://www.allaccessservices.com/resources/spec-sheets',
  },
  {
    id: 'jlg-10000',
    category: 'telehandlers',
    name: 'JLG G10-55A',
    height: 55,
    reach: 43,
    capacity: 10000,
    power: 'Diesel',
    width: 8.5,
    weight: 29500,
    dailyRate: 695,
    weeklyRate: 1950,
    monthlyRate: 5200,
    imageUrl: 'https://www.allaccessservices.com/site-assets/equipment/skytrak-10054.jpg',
    specSheet: 'https://www.allaccessservices.com/resources/spec-sheets',
  },

  // Low Level Access
  {
    id: 'jlg-10ft',
    category: 'low-level-access',
    name: 'JLG PersonalLift 10S',
    height: 10,
    reach: 0,
    capacity: 300,
    power: 'Electric',
    width: 2.2,
    weight: 850,
    dailyRate: 75,
    weeklyRate: 200,
    monthlyRate: 500,
    imageUrl: 'https://www.allaccessservices.com/site-assets/equipment/jlg-es1932.jpg',
    specSheet: 'https://www.allaccessservices.com/resources/spec-sheets',
  },
  {
    id: 'jlg-15ft',
    category: 'low-level-access',
    name: 'JLG PersonalLift 15S',
    height: 15,
    reach: 0,
    capacity: 300,
    power: 'Electric',
    width: 2.2,
    weight: 1200,
    dailyRate: 95,
    weeklyRate: 260,
    monthlyRate: 650,
    imageUrl: 'https://www.allaccessservices.com/site-assets/equipment/jlg-es1932.jpg',
    specSheet: 'https://www.allaccessservices.com/resources/spec-sheets',
  },
  {
    id: 'jlg-20ft',
    category: 'low-level-access',
    name: 'JLG PersonalLift 20S',
    height: 20,
    reach: 0,
    capacity: 300,
    power: 'Electric',
    width: 2.2,
    weight: 1600,
    dailyRate: 115,
    weeklyRate: 320,
    monthlyRate: 800,
    imageUrl: 'https://www.allaccessservices.com/site-assets/equipment/jlg-es1932.jpg',
    specSheet: 'https://www.allaccessservices.com/resources/spec-sheets',
  },
];

export const powerSources = ['Electric', 'Diesel'];
export const heightRanges = [
  { label: 'Under 20 ft', min: 0, max: 20 },
  { label: '20-40 ft', min: 20, max: 40 },
  { label: '40-60 ft', min: 40, max: 60 },
  { label: '60-100 ft', min: 60, max: 100 },
  { label: '100+ ft', min: 100, max: 200 },
];
export const widthRanges = [
  { label: 'Compact (under 3 ft)', min: 0, max: 3 },
  { label: 'Standard (3-9 ft)', min: 3, max: 9 },
  { label: 'Wide (9+ ft)', min: 9, max: 20 },
];