// Complete rental inventory with real equipment specs
export const rentalModels = [
  // SCISSOR LIFTS
  {
    id: 'jlg-1330se',
    category: 'scissor-lifts',
    name: 'JLG 1330SE',
    height: 13,
    reach: 0,
    capacity: 440,
    power: 'Electric',
    width: 30,
    weight: 1800,
    dailyRate: null,
    weeklyRate: null,
    monthlyRate: null,
    imageUrl: null,
    specSheet: 'https://www.allaccessservices.com/resources/',
  },
  {
    id: 'jlg-1932r',
    category: 'scissor-lifts',
    name: 'JLG 1932R',
    height: 19,
    reach: 0,
    capacity: 550,
    power: 'Electric',
    width: 32,
    weight: 2200,
    dailyRate: null,
    weeklyRate: null,
    monthlyRate: null,
    imageUrl: null,
    specSheet: 'https://www.allaccessservices.com/resources/',
  },
  {
    id: 'jlg-2632r',
    category: 'scissor-lifts',
    name: 'JLG 2632R',
    height: 26,
    reach: 0,
    capacity: 800,
    power: 'Electric',
    width: 32,
    weight: 4500,
    dailyRate: null,
    weeklyRate: null,
    monthlyRate: null,
    imageUrl: null,
    specSheet: 'https://www.allaccessservices.com/resources/',
  },
  {
    id: 'jlg-3246es',
    category: 'scissor-lifts',
    name: 'JLG 3246ES',
    height: 32,
    reach: 0,
    capacity: 800,
    power: 'Electric',
    width: 46,
    weight: 6500,
    dailyRate: null,
    weeklyRate: null,
    monthlyRate: null,
    imageUrl: null,
    specSheet: 'https://www.allaccessservices.com/resources/',
  },
  {
    id: 'jlg-4045r',
    category: 'scissor-lifts',
    name: 'JLG 4045R',
    height: 40,
    reach: 0,
    capacity: 800,
    power: 'Electric',
    width: 45,
    weight: 8200,
    dailyRate: null,
    weeklyRate: null,
    monthlyRate: null,
    imageUrl: null,
    specSheet: 'https://www.allaccessservices.com/resources/',
  },

  // STRAIGHT BOOM LIFTS
  {
    id: 'jlg-400s',
    category: 'boom-lifts',
    name: 'JLG 400S',
    height: 40,
    reach: 40,
    capacity: 500,
    power: 'Diesel',
    width: 96,
    weight: 10500,
    dailyRate: null,
    weeklyRate: null,
    monthlyRate: null,
    imageUrl: null,
    specSheet: 'https://www.allaccessservices.com/resources/',
  },
  {
    id: 'jlg-460sj',
    category: 'boom-lifts',
    name: 'JLG 460SJ',
    height: 46,
    reach: 46,
    capacity: 500,
    power: 'Diesel',
    width: 90,
    weight: 12500,
    dailyRate: null,
    weeklyRate: null,
    monthlyRate: null,
    imageUrl: null,
    specSheet: 'https://www.allaccessservices.com/resources/',
  },
  {
    id: 'jlg-600s',
    category: 'boom-lifts',
    name: 'JLG 600S',
    height: 60,
    reach: 60,
    capacity: 500,
    power: 'Diesel',
    width: 96,
    weight: 14200,
    dailyRate: null,
    weeklyRate: null,
    monthlyRate: null,
    imageUrl: null,
    specSheet: 'https://www.allaccessservices.com/resources/',
  },
  {
    id: 'jlg-660sj',
    category: 'boom-lifts',
    name: 'JLG 660SJ',
    height: 66,
    reach: 66,
    capacity: 500,
    power: 'Diesel',
    width: 96,
    weight: 16000,
    dailyRate: null,
    weeklyRate: null,
    monthlyRate: null,
    imageUrl: null,
    specSheet: 'https://www.allaccessservices.com/resources/',
  },
  {
    id: 'jlg-860sj',
    category: 'boom-lifts',
    name: 'JLG 860SJ',
    height: 86,
    reach: 86,
    capacity: 500,
    power: 'Diesel',
    width: 96,
    weight: 18500,
    dailyRate: null,
    weeklyRate: null,
    monthlyRate: null,
    imageUrl: null,
    specSheet: 'https://www.allaccessservices.com/resources/',
  },
  {
    id: 'jlg-1350sjp',
    category: 'boom-lifts',
    name: 'JLG 1350SJP',
    height: 135,
    reach: 110,
    capacity: 500,
    power: 'Diesel',
    width: 98,
    weight: 30000,
    dailyRate: null,
    weeklyRate: null,
    monthlyRate: null,
    imageUrl: null,
    specSheet: 'https://www.allaccessservices.com/resources/',
  },

  // ARTICULATING BOOM LIFTS
  {
    id: 'jlg-340aj',
    category: 'articulating-booms',
    name: 'JLG 340AJ',
    height: 34,
    reach: 34,
    capacity: 500,
    power: 'Diesel',
    width: 90,
    weight: 11000,
    dailyRate: null,
    weeklyRate: null,
    monthlyRate: null,
    imageUrl: null,
    specSheet: 'https://www.allaccessservices.com/resources/',
  },
  {
    id: 'jlg-450aj',
    category: 'articulating-booms',
    name: 'JLG 450AJ',
    height: 45,
    reach: 45,
    capacity: 500,
    power: 'Diesel',
    width: 90,
    weight: 12000,
    dailyRate: null,
    weeklyRate: null,
    monthlyRate: null,
    imageUrl: null,
    specSheet: 'https://www.allaccessservices.com/resources/',
  },
  {
    id: 'jlg-600aj',
    category: 'articulating-booms',
    name: 'JLG 600AJ',
    height: 60,
    reach: 60,
    capacity: 500,
    power: 'Diesel',
    width: 96,
    weight: 14500,
    dailyRate: null,
    weeklyRate: null,
    monthlyRate: null,
    imageUrl: null,
    specSheet: 'https://www.allaccessservices.com/resources/',
  },
  {
    id: 'jlg-800aj',
    category: 'articulating-booms',
    name: 'JLG 800AJ',
    height: 80,
    reach: 80,
    capacity: 660,
    power: 'Diesel',
    width: 96,
    weight: 19200,
    dailyRate: null,
    weeklyRate: null,
    monthlyRate: null,
    imageUrl: null,
    specSheet: 'https://www.allaccessservices.com/resources/',
  },

  // TELEHANDLERS
  {
    id: 'jlg-943',
    category: 'telehandlers',
    name: 'JLG 943',
    height: 43,
    reach: 43,
    capacity: 9000,
    power: 'Diesel',
    width: 102,
    weight: 22000,
    dailyRate: null,
    weeklyRate: null,
    monthlyRate: null,
    imageUrl: null,
    specSheet: 'https://www.allaccessservices.com/resources/',
  },
  {
    id: 'jlg-1055',
    category: 'telehandlers',
    name: 'JLG 1055',
    height: 55,
    reach: 43,
    capacity: 11000,
    power: 'Diesel',
    width: 102,
    weight: 25000,
    dailyRate: null,
    weeklyRate: null,
    monthlyRate: null,
    imageUrl: null,
    specSheet: 'https://www.allaccessservices.com/resources/',
  },
  {
    id: 'jlg-1255',
    category: 'telehandlers',
    name: 'JLG 1255',
    height: 55,
    reach: 54,
    capacity: 12000,
    power: 'Diesel',
    width: 102,
    weight: 26500,
    dailyRate: null,
    weeklyRate: null,
    monthlyRate: null,
    imageUrl: null,
    specSheet: 'https://www.allaccessservices.com/resources/',
  },

  // FORKLIFTS
  {
    id: 'hyster-s50a',
    category: 'forklifts',
    name: 'Hyster S50A',
    height: 0,
    reach: 0,
    capacity: 5000,
    power: 'Propane',
    width: 48,
    weight: 4200,
    dailyRate: null,
    weeklyRate: null,
    monthlyRate: null,
    imageUrl: null,
    specSheet: 'https://www.allaccessservices.com/resources/',
  },
  {
    id: 'hyster-h80ft',
    category: 'forklifts',
    name: 'Hyster H80FT',
    height: 0,
    reach: 0,
    capacity: 8000,
    power: 'Diesel',
    width: 48,
    weight: 5200,
    dailyRate: null,
    weeklyRate: null,
    monthlyRate: null,
    imageUrl: null,
    specSheet: 'https://www.allaccessservices.com/resources/',
  },
  {
    id: 'hyster-h120ft',
    category: 'forklifts',
    name: 'Hyster H120FT',
    height: 0,
    reach: 0,
    capacity: 12000,
    power: 'Diesel',
    width: 52,
    weight: 6500,
    dailyRate: null,
    weeklyRate: null,
    monthlyRate: null,
    imageUrl: null,
    specSheet: 'https://www.allaccessservices.com/resources/',
  },
];

export const rentalCategories = [
  {
    slug: 'scissor-lifts',
    name: 'Scissor Lifts',
    image: null,
    gradientFrom: '#f97316',
    gradientTo: '#ea580c',
    description: 'Electric & diesel for indoor & rough terrain'
  },
  {
    slug: 'boom-lifts',
    name: 'Straight Booms',
    image: null,
    gradientFrom: '#3b82f6',
    gradientTo: '#1d4ed8',
    description: 'Straight reach lifts up to 135 ft'
  },
  {
    slug: 'articulating-booms',
    name: 'Articulating Booms',
    image: null,
    gradientFrom: '#7c3aed',
    gradientTo: '#6d28d9',
    description: 'Articulating reach lifts up to 80 ft'
  },
  {
    slug: 'telehandlers',
    name: 'Telehandlers',
    image: null,
    gradientFrom: '#eab308',
    gradientTo: '#ca8a04',
    description: 'Versatile material handling up to 12,000 lb'
  },
  {
    slug: 'forklifts',
    name: 'Forklifts',
    image: null,
    gradientFrom: '#22c55e',
    gradientTo: '#16a34a',
    description: 'Warehouse & rough terrain lift trucks'
  },
];

export const powerSources = ['Electric', 'Diesel', 'Propane'];
export const heightRanges = [
  { label: 'Under 20 ft', min: 0, max: 20 },
  { label: '20-40 ft', min: 20, max: 40 },
  { label: '40-60 ft', min: 40, max: 60 },
  { label: '60-100 ft', min: 60, max: 100 },
  { label: '100+ ft', min: 100, max: 200 },
];
export const widthRanges = [
  { label: 'Compact (under 50 in)', min: 0, max: 50 },
  { label: 'Standard (50-96 in)', min: 50, max: 96 },
  { label: 'Wide (96+ in)', min: 96, max: 120 },
];