// Complete rental inventory matching allaccessservices.com
export const rentalModels = [
  // SCISSOR LIFTS - ELECTRIC
  {
    id: 'jlg-es1330m',
    category: 'scissor-lifts',
    name: 'JLG ES1330M',
    height: 13,
    reach: 0,
    capacity: 440,
    power: 'Electric',
    width: 30,
    weight: 1800,
    dailyRate: null,
    weeklyRate: null,
    monthlyRate: null,
    imageUrl: 'https://www.allaccessservices.com/fckimages/pages/equipment-rentals/scissor_lift.jpg',
    specSheet: 'https://www.allaccessservices.com/fckimages/pdf/12-specs.pdf',
  },
  {
    id: 'jlg-es1930m',
    category: 'scissor-lifts',
    name: 'JLG ES1930M',
    height: 19,
    reach: 0,
    capacity: 550,
    power: 'Electric',
    width: 32,
    weight: 2350,
    dailyRate: null,
    weeklyRate: null,
    monthlyRate: null,
    imageUrl: 'https://www.allaccessservices.com/fckimages/pages/equipment-rentals/scissor_lift.jpg',
    specSheet: 'https://www.allaccessservices.com/fckimages/pdf/19specs.pdf',
  },
  {
    id: 'jlg-2632es',
    category: 'scissor-lifts',
    name: 'JLG 2632ES',
    height: 26,
    reach: 0,
    capacity: 800,
    power: 'Electric',
    width: 32,
    weight: 3748,
    dailyRate: null,
    weeklyRate: null,
    monthlyRate: null,
    imageUrl: 'https://www.allaccessservices.com/fckimages/pages/equipment-rentals/scissor_lift.jpg',
    specSheet: 'https://www.allaccessservices.com/fckimages/pdf/26specs.pdf',
  },
  {
    id: 'jlg-3246es',
    category: 'scissor-lifts',
    name: 'JLG 3246ES',
    height: 32,
    reach: 0,
    capacity: 800,
    power: 'Electric',
    width: 46,
    weight: 5236,
    dailyRate: null,
    weeklyRate: null,
    monthlyRate: null,
    imageUrl: 'https://www.allaccessservices.com/fckimages/pages/equipment-rentals/scissor_lift.jpg',
    specSheet: 'https://www.allaccessservices.com/fckimages/pdf/32specs.pdf',
  },
  {
    id: 'jlg-4069le',
    category: 'scissor-lifts',
    name: 'JLG 4069LE',
    height: 40,
    reach: 0,
    capacity: 1000,
    power: 'Electric',
    width: 40,
    weight: 6800,
    dailyRate: null,
    weeklyRate: null,
    monthlyRate: null,
    imageUrl: 'https://www.allaccessservices.com/fckimages/pages/equipment-rentals/scissor_lift.jpg',
    specSheet: 'https://www.allaccessservices.com/fckimages/pdf/LE-Series-Spec-Sheet_1.pdf',
  },

  // SCISSOR LIFTS - ROUGH TERRAIN
  {
    id: 'jlg-rt2669',
    category: 'scissor-lifts',
    name: 'JLG RT 2669',
    height: 26,
    reach: 0,
    capacity: 1350,
    power: 'Diesel',
    width: 66,
    weight: 5880,
    dailyRate: null,
    weeklyRate: null,
    monthlyRate: null,
    imageUrl: 'https://www.allaccessservices.com/fckimages/pages/equipment-rentals/scissor_lift.jpg',
    specSheet: 'https://www.allaccessservices.com/fckimages/pdf/RT2669SpecSheet.pdf',
  },
  {
    id: 'jlg-rt3369',
    category: 'scissor-lifts',
    name: 'JLG RT 3369',
    height: 33,
    reach: 0,
    capacity: 1500,
    power: 'Diesel',
    width: 68,
    weight: 7150,
    dailyRate: null,
    weeklyRate: null,
    monthlyRate: null,
    imageUrl: 'https://www.allaccessservices.com/fckimages/pages/equipment-rentals/scissor_lift.jpg',
    specSheet: 'https://www.allaccessservices.com/fckimages/pdf/RT3369SpecSheet.pdf',
  },
  {
    id: 'jlg-rt3394',
    category: 'scissor-lifts',
    name: 'JLG RT 3394',
    height: 33,
    reach: 0,
    capacity: 1500,
    power: 'Diesel',
    width: 66,
    weight: 7500,
    dailyRate: null,
    weeklyRate: null,
    monthlyRate: null,
    imageUrl: 'https://www.allaccessservices.com/fckimages/pages/equipment-rentals/scissor_lift.jpg',
    specSheet: 'https://www.allaccessservices.com/fckimages/pdf/RT3394SpecSheet.pdf',
  },
  {
    id: 'jlg-rt4069',
    category: 'scissor-lifts',
    name: 'JLG RT 4069',
    height: 40,
    reach: 0,
    capacity: 1500,
    power: 'Diesel',
    width: 72,
    weight: 8920,
    dailyRate: null,
    weeklyRate: null,
    monthlyRate: null,
    imageUrl: 'https://www.allaccessservices.com/fckimages/pages/equipment-rentals/scissor_lift.jpg',
    specSheet: 'https://www.allaccessservices.com/fckimages/pdf/RT4069SpecSheet.pdf',
  },
  {
    id: 'jlg-rt4394',
    category: 'scissor-lifts',
    name: 'JLG RT 4394',
    height: 43,
    reach: 0,
    capacity: 1500,
    power: 'Diesel',
    width: 72,
    weight: 9100,
    dailyRate: null,
    weeklyRate: null,
    monthlyRate: null,
    imageUrl: 'https://www.allaccessservices.com/fckimages/pages/equipment-rentals/scissor_lift.jpg',
    specSheet: 'https://www.allaccessservices.com/fckimages/pdf/RT4394ScissorSpecSheet.pdf',
  },
  {
    id: 'jlg-rt4769',
    category: 'scissor-lifts',
    name: 'JLG RT 4769',
    height: 47,
    reach: 0,
    capacity: 1500,
    power: 'Diesel',
    width: 82,
    weight: 10800,
    dailyRate: null,
    weeklyRate: null,
    monthlyRate: null,
    imageUrl: 'https://www.allaccessservices.com/fckimages/pages/equipment-rentals/scissor_lift.jpg',
    specSheet: 'https://www.allaccessservices.com/fckimages/pdf/RT4769SpecSheet.pdf',
  },
  {
    id: 'jlg-rt5394',
    category: 'scissor-lifts',
    name: 'JLG RT 5394',
    height: 53,
    reach: 0,
    capacity: 1500,
    power: 'Diesel',
    width: 82,
    weight: 11500,
    dailyRate: null,
    weeklyRate: null,
    monthlyRate: null,
    imageUrl: 'https://www.allaccessservices.com/fckimages/pages/equipment-rentals/scissor_lift.jpg',
    specSheet: 'https://www.allaccessservices.com/fckimages/pdf/RT5394ScissorSpecSheet.pdf',
  },

  // STRAIGHT BOOM LIFTS
  {
    id: 'jlg-400s',
    category: 'straight-boom-lifts',
    name: 'JLG 400S',
    height: 40,
    reach: 22,
    capacity: 500,
    power: 'Diesel',
    width: 96,
    weight: 13700,
    dailyRate: null,
    weeklyRate: null,
    monthlyRate: null,
    imageUrl: 'https://www.allaccessservices.com/fckimages/pages/equipment-rentals/boom_edited.jpg',
    specSheet: 'https://www.allaccessservices.com/fckimages/pdf/400-Series-Spec-Sheet.pdf',
  },
  {
    id: 'jlg-460sj',
    category: 'straight-boom-lifts',
    name: 'JLG 460SJ',
    height: 46,
    reach: 46,
    capacity: 500,
    power: 'Diesel',
    width: 90,
    weight: 12500,
    dailyRate: null,
    weeklyRate: null,
    monthlyRate: null,
    imageUrl: 'https://www.allaccessservices.com/fckimages/pages/equipment-rentals/boom_edited.jpg',
    specSheet: 'https://www.allaccessservices.com/fckimages/pdf/460-Series-Spec-Sheet.pdf',
  },
  {
    id: 'jlg-600s',
    category: 'straight-boom-lifts',
    name: 'JLG 600S',
    height: 60,
    reach: 36,
    capacity: 500,
    power: 'Diesel',
    width: 96,
    weight: 18280,
    dailyRate: null,
    weeklyRate: null,
    monthlyRate: null,
    imageUrl: 'https://www.allaccessservices.com/fckimages/pages/equipment-rentals/boom_edited.jpg',
    specSheet: 'https://www.allaccessservices.com/fckimages/pdf/600-Series-Spec-Sheet.pdf',
  },
  {
    id: 'jlg-660sj',
    category: 'straight-boom-lifts',
    name: 'JLG 660SJ',
    height: 66,
    reach: 66,
    capacity: 500,
    power: 'Diesel',
    width: 96,
    weight: 16000,
    dailyRate: null,
    weeklyRate: null,
    monthlyRate: null,
    imageUrl: 'https://www.allaccessservices.com/fckimages/pages/equipment-rentals/boom_edited.jpg',
    specSheet: 'https://www.allaccessservices.com/fckimages/pdf/660-Series-Spec-Sheet.pdf',
  },
  {
    id: 'jlg-860sj',
    category: 'straight-boom-lifts',
    name: 'JLG 860SJ',
    height: 86,
    reach: 86,
    capacity: 500,
    power: 'Diesel',
    width: 96,
    weight: 18500,
    dailyRate: null,
    weeklyRate: null,
    monthlyRate: null,
    imageUrl: 'https://www.allaccessservices.com/fckimages/pages/equipment-rentals/boom_edited.jpg',
    specSheet: 'https://www.allaccessservices.com/fckimages/pdf/860-Series-Spec-Sheet.pdf',
  },
  {
    id: 'jlg-1200sjp',
    category: 'straight-boom-lifts',
    name: 'JLG 1200SJP',
    height: 120,
    reach: 80,
    capacity: 500,
    power: 'Diesel',
    width: 98,
    weight: 48000,
    dailyRate: null,
    weeklyRate: null,
    monthlyRate: null,
    imageUrl: 'https://www.allaccessservices.com/fckimages/pages/equipment-rentals/boom_edited.jpg',
    specSheet: 'https://www.allaccessservices.com/fckimages/pdf/1200-Spec-Sheet.pdf',
  },
  {
    id: 'jlg-1350sjp',
    category: 'straight-boom-lifts',
    name: 'JLG 1350SJP',
    height: 135,
    reach: 80,
    capacity: 500,
    power: 'Diesel',
    width: 98,
    weight: 55000,
    dailyRate: null,
    weeklyRate: null,
    monthlyRate: null,
    imageUrl: 'https://www.allaccessservices.com/fckimages/pages/equipment-rentals/boom_edited.jpg',
    specSheet: 'https://www.allaccessservices.com/fckimages/pdf/1350-Spec-Sheet.pdf',
  },

  // KNUCKLE BOOMS - ELECTRIC
  {
    id: 'jlg-e300ajp',
    category: 'articulating-boom-lifts',
    name: 'JLG E300AJP',
    height: 30,
    reach: 20,
    capacity: 500,
    power: 'Electric',
    width: 72,
    weight: 8710,
    dailyRate: null,
    weeklyRate: null,
    monthlyRate: null,
    imageUrl: 'https://www.allaccessservices.com/fckimages/pages/equipment-rentals/knuckle-boom.jpg',
    specSheet: 'https://www.allaccessservices.com/fckimages/pdf/E-Series-Boom-Lifts-Spec-Sheet_1.pdf',
  },
  {
    id: 'jlg-e400ajp',
    category: 'articulating-boom-lifts',
    name: 'JLG E400AJP',
    height: 40,
    reach: 40,
    capacity: 500,
    power: 'Electric',
    width: 84,
    weight: 10500,
    dailyRate: null,
    weeklyRate: null,
    monthlyRate: null,
    imageUrl: 'https://www.allaccessservices.com/fckimages/pages/equipment-rentals/boom_edited.jpg',
    specSheet: 'https://www.allaccessservices.com/fckimages/pdf/E-Series-Boom-Lifts-Spec-Sheet_2.pdf',
  },
  {
    id: 'jlg-e450ajp',
    category: 'articulating-boom-lifts',
    name: 'JLG E450AJP',
    height: 45,
    reach: 45,
    capacity: 500,
    power: 'Electric',
    width: 84,
    weight: 11000,
    dailyRate: null,
    weeklyRate: null,
    monthlyRate: null,
    imageUrl: 'https://www.allaccessservices.com/fckimages/pages/equipment-rentals/boom_edited.jpg',
    specSheet: 'https://www.allaccessservices.com/fckimages/pdf/450AJ-Articulating-Boom-Spec-Sheet.pdf',
  },

  // KNUCKLE BOOMS - GAS
  {
    id: 'jlg-450aj',
    category: 'articulating-boom-lifts',
    name: 'JLG 450AJ',
    height: 45,
    reach: 25,
    capacity: 500,
    power: 'Diesel',
    width: 90,
    weight: 14900,
    dailyRate: null,
    weeklyRate: null,
    monthlyRate: null,
    imageUrl: 'https://www.allaccessservices.com/fckimages/pages/equipment-rentals/boom_edited.jpg',
    specSheet: 'https://www.allaccessservices.com/fckimages/pdf/450AJ-Articulating-Boom-Spec-Sheet_4.pdf',
  },
  {
    id: 'jlg-340aj',
    category: 'articulating-boom-lifts',
    name: 'JLG 340AJ',
    height: 34,
    reach: 18,
    capacity: 500,
    power: 'Diesel',
    width: 90,
    weight: 12000,
    dailyRate: null,
    weeklyRate: null,
    monthlyRate: null,
    imageUrl: 'https://www.allaccessservices.com/fckimages/pages/equipment-rentals/knuckle-boom.jpg',
    specSheet: 'https://www.allaccessservices.com/fckimages/pdf/340AJ-Spec-Sheet.pdf',
  },
  {
    id: 'jlg-460aj',
    category: 'articulating-boom-lifts',
    name: 'JLG 460AJ',
    height: 46,
    reach: 24,
    capacity: 500,
    power: 'Diesel',
    width: 90,
    weight: 16000,
    dailyRate: null,
    weeklyRate: null,
    monthlyRate: null,
    imageUrl: 'https://www.allaccessservices.com/fckimages/pages/equipment-rentals/knuckle-boom.jpg',
    specSheet: 'https://www.allaccessservices.com/fckimages/pdf/460AJ-Spec-Sheet.pdf',
  },
  {
    id: 'jlg-600aj',
    category: 'articulating-boom-lifts',
    name: 'JLG 600AJ',
    height: 60,
    reach: 35,
    capacity: 500,
    power: 'Diesel',
    width: 96,
    weight: 24000,
    dailyRate: null,
    weeklyRate: null,
    monthlyRate: null,
    imageUrl: 'https://www.allaccessservices.com/fckimages/pages/equipment-rentals/knuckle-boom.jpg',
    specSheet: 'https://www.allaccessservices.com/fckimages/pdf/600-Series-Spec-Sheet_3.pdf',
  },
  {
    id: 'jlg-800aj-knuckle',
    category: 'articulating-boom-lifts',
    name: 'JLG 800AJ Knuckle',
    height: 80,
    reach: 50,
    capacity: 660,
    power: 'Diesel',
    width: 96,
    weight: 33700,
    dailyRate: null,
    weeklyRate: null,
    monthlyRate: null,
    imageUrl: 'https://www.allaccessservices.com/fckimages/pages/equipment-rentals/knuckle-boom.jpg',
    specSheet: 'https://www.allaccessservices.com/fckimages/pdf/800-Series-Spec-Sheet_2.pdf',
  },

  // CRAWLER BOOMS
  {
    id: 'jlg-x500aj',
    category: 'articulating-boom-lifts',
    name: 'JLG X500AJ',
    height: 50,
    reach: 50,
    capacity: 500,
    power: 'Diesel',
    width: 96,
    weight: 16500,
    dailyRate: null,
    weeklyRate: null,
    monthlyRate: null,
    imageUrl: 'https://www.allaccessservices.com/fckimages/pages/equipment-rentals/boom_edited.jpg',
    specSheet: 'https://www.allaccessservices.com/fckimages/pdf/Compact-Crawler-Boom-Brochure_4.pdf',
  },
  {
    id: 'jlg-x770aj',
    category: 'articulating-boom-lifts',
    name: 'JLG X770AJ',
    height: 80,
    reach: 80,
    capacity: 500,
    power: 'Diesel',
    width: 96,
    weight: 22000,
    dailyRate: null,
    weeklyRate: null,
    monthlyRate: null,
    imageUrl: 'https://www.allaccessservices.com/fckimages/pages/equipment-rentals/boom_edited.jpg',
    specSheet: 'https://www.allaccessservices.com/fckimages/pdf/Compact-Crawler-Boom-Brochure_4.pdf',
  },
  {
    id: 'jlg-x1000aj',
    category: 'articulating-boom-lifts',
    name: 'JLG X1000AJ',
    height: 100,
    reach: 100,
    capacity: 500,
    power: 'Diesel',
    width: 96,
    weight: 28000,
    dailyRate: null,
    weeklyRate: null,
    monthlyRate: null,
    imageUrl: 'https://www.allaccessservices.com/fckimages/pages/equipment-rentals/boom_edited.jpg',
    specSheet: 'https://www.allaccessservices.com/fckimages/pdf/Compact-Crawler-Boom-Brochure_4.pdf',
  },

  // TOW PRO BOOMS
  {
    id: 'jlg-t350j',
    category: 'articulating-boom-lifts',
    name: 'JLG T350J',
    height: 35,
    reach: 35,
    capacity: 500,
    power: 'Diesel',
    width: 96,
    weight: 8500,
    dailyRate: null,
    weeklyRate: null,
    monthlyRate: null,
    imageUrl: 'https://www.allaccessservices.com/fckimages/pages/equipment-rentals/boom_edited.jpg',
    specSheet: 'https://www.allaccessservices.com/fckimages/pdf/T350-Spec-Sheet.pdf',
  },
  {
    id: 'jlg-et350j',
    category: 'articulating-boom-lifts',
    name: 'JLG ET350J',
    height: 35,
    reach: 35,
    capacity: 500,
    power: 'Electric',
    width: 96,
    weight: 8000,
    dailyRate: null,
    weeklyRate: null,
    monthlyRate: null,
    imageUrl: 'https://www.allaccessservices.com/fckimages/pages/equipment-rentals/boom_edited.jpg',
    specSheet: 'https://www.allaccessservices.com/fckimages/pdf/ET350-Spec-Sheet.pdf',
  },
  {
    id: 'jlg-t500j',
    category: 'articulating-boom-lifts',
    name: 'JLG T500J',
    height: 50,
    reach: 50,
    capacity: 500,
    power: 'Diesel',
    width: 96,
    weight: 10000,
    dailyRate: null,
    weeklyRate: null,
    monthlyRate: null,
    imageUrl: 'https://www.allaccessservices.com/fckimages/pages/equipment-rentals/boom_edited.jpg',
    specSheet: 'https://www.allaccessservices.com/fckimages/pdf/T500J-Spec-Sheet.pdf',
  },

  // TELEHANDLERS
  {
    id: 'jlg-g9-43a',
    category: 'telehandlers',
    name: 'JLG G9-43A',
    height: 0,
    reach: 43,
    capacity: 9000,
    power: 'Diesel',
    width: 96,
    weight: 19700,
    dailyRate: null,
    weeklyRate: null,
    monthlyRate: null,
    imageUrl: 'https://www.allaccessservices.com/fckimages/pages/equipment-rentals/telehandler_edited.jpg',
    specSheet: 'https://www.allaccessservices.com/fckimages/pdf/G9-43A-Spec-Sheet.pdf',
  },
  {
    id: 'jlg-g12-55a',
    category: 'telehandlers',
    name: 'JLG G12-55A',
    height: 0,
    reach: 55,
    capacity: 12000,
    power: 'Diesel',
    width: 100,
    weight: 25100,
    dailyRate: null,
    weeklyRate: null,
    monthlyRate: null,
    imageUrl: 'https://www.allaccessservices.com/fckimages/pages/equipment-rentals/telehandler_edited.jpg',
    specSheet: 'https://www.allaccessservices.com/fckimages/pdf/G12-55A-Spec-Sheet.pdf',
  },
  {
    id: 'jlg-519',
    category: 'telehandlers',
    name: 'JLG 519',
    height: 0,
    reach: 19,
    capacity: 5000,
    power: 'Diesel',
    width: 72,
    weight: 9200,
    dailyRate: null,
    weeklyRate: null,
    monthlyRate: null,
    imageUrl: 'https://www.allaccessservices.com/fckimages/pages/equipment-rentals/telehandler_edited.jpg',
    specSheet: 'https://www.allaccessservices.com/resources/',
  },
  {
    id: 'jlg-g518a',
    category: 'telehandlers',
    name: 'JLG G5-18A',
    height: 18,
    reach: 18,
    capacity: 5000,
    power: 'Diesel',
    width: 84,
    weight: 8800,
    dailyRate: null,
    weeklyRate: null,
    monthlyRate: null,
    imageUrl: 'https://www.allaccessservices.com/fckimages/pages/equipment-rentals/telehandler_edited.jpg',
    specSheet: 'https://www.allaccessservices.com/fckimages/pdf/G5-18A-Spec-Sheet.pdf',
  },
  {
    id: 'skytrak-10054',
    category: 'telehandlers',
    name: 'SkyTrak 10054',
    height: 0,
    reach: 54,
    capacity: 10000,
    power: 'Diesel',
    width: 99,
    weight: 28300,
    dailyRate: null,
    weeklyRate: null,
    monthlyRate: null,
    imageUrl: 'https://www.allaccessservices.com/fckimages/pages/equipment-rentals/telehandler_edited.jpg',
    specSheet: 'https://www.allaccessservices.com/resources/',
  },
  {
    id: 'skytrak-6042',
    category: 'telehandlers',
    name: 'Skytrak 6042',
    height: 42,
    reach: 42,
    capacity: 7000,
    power: 'Diesel',
    width: 84,
    weight: 9200,
    dailyRate: null,
    weeklyRate: null,
    monthlyRate: null,
    imageUrl: 'https://www.allaccessservices.com/fckimages/pages/equipment-rentals/telehandler_edited.jpg',
    specSheet: 'https://www.allaccessservices.com/fckimages/pdf/SkyTrak_6042_Spec_Sheet.pdf',
  },
  {
    id: 'skytrak-8042',
    category: 'telehandlers',
    name: 'Skytrak 8042',
    height: 42,
    reach: 42,
    capacity: 8000,
    power: 'Diesel',
    width: 84,
    weight: 9800,
    dailyRate: null,
    weeklyRate: null,
    monthlyRate: null,
    imageUrl: 'https://www.allaccessservices.com/fckimages/pages/equipment-rentals/telehandler_edited.jpg',
    specSheet: 'https://www.allaccessservices.com/fckimages/pdf/SkyTrak_8042_Spec_Sheet.pdf',
  },
  {
    id: 'jlg-943',
    category: 'telehandlers',
    name: 'JLG 943',
    height: 43,
    reach: 43,
    capacity: 9000,
    power: 'Diesel',
    width: 102,
    weight: 22000,
    dailyRate: null,
    weeklyRate: null,
    monthlyRate: null,
    imageUrl: 'https://www.allaccessservices.com/fckimages/pages/equipment-rentals/telehandler_edited.jpg',
    specSheet: 'https://www.allaccessservices.com/fckimages/pdf/JLG-943-Spec-Sheet.pdf',
  },
  {
    id: 'jlg-1055',
    category: 'telehandlers',
    name: 'JLG 1055',
    height: 55,
    reach: 43,
    capacity: 10000,
    power: 'Diesel',
    width: 102,
    weight: 25000,
    dailyRate: null,
    weeklyRate: null,
    monthlyRate: null,
    imageUrl: 'https://www.allaccessservices.com/fckimages/pages/equipment-rentals/telehandler_edited.jpg',
    specSheet: 'https://www.allaccessservices.com/fckimages/pdf/1055-Telehandler-SpecSheet.pdf',
  },
  {
    id: 'jlg-1075',
    category: 'telehandlers',
    name: 'JLG 1075',
    height: 75,
    reach: 42,
    capacity: 10075,
    power: 'Diesel',
    width: 102,
    weight: 28500,
    dailyRate: null,
    weeklyRate: null,
    monthlyRate: null,
    imageUrl: 'https://www.allaccessservices.com/fckimages/pages/equipment-rentals/telehandler_edited.jpg',
    specSheet: 'https://www.allaccessservices.com/fckimages/pdf/1075_SPECS_AND_LOAD_CHART.pdf',
  },
  {
    id: 'jlg-1255',
    category: 'telehandlers',
    name: 'JLG 1255',
    height: 55,
    reach: 54,
    capacity: 12000,
    power: 'Diesel',
    width: 102,
    weight: 26500,
    dailyRate: null,
    weeklyRate: null,
    monthlyRate: null,
    imageUrl: 'https://www.allaccessservices.com/fckimages/pages/equipment-rentals/telehandler_edited.jpg',
    specSheet: 'https://www.allaccessservices.com/fckimages/pdf/1255-Telehandler-SpecSheet.pdf',
  },
  {
    id: 'jlg-1644th',
    category: 'telehandlers',
    name: 'JLG 1644TH',
    height: 44,
    reach: 44,
    capacity: 16755,
    power: 'Diesel',
    width: 108,
    weight: 32000,
    dailyRate: null,
    weeklyRate: null,
    monthlyRate: null,
    imageUrl: 'https://www.allaccessservices.com/fckimages/pages/equipment-rentals/telehandler_edited.jpg',
    specSheet: 'https://www.allaccessservices.com/fckimages/pdf/1644-Telehandler-Spec-Sheet.pdf',
  },
  {
    id: 'jlg-1732th',
    category: 'telehandlers',
    name: 'JLG 1732TH',
    height: 32,
    reach: 32,
    capacity: 17000,
    power: 'Diesel',
    width: 108,
    weight: 33500,
    dailyRate: null,
    weeklyRate: null,
    monthlyRate: null,
    imageUrl: 'https://www.allaccessservices.com/fckimages/pages/equipment-rentals/telehandler_edited.jpg',
    specSheet: 'https://www.allaccessservices.com/fckimages/pdf/1732-Telehandler-Spec-Sheet.pdf',
  },
  {
    id: 'jlg-r1385',
    category: 'telehandlers',
    name: 'JLG R1385',
    height: 60,
    reach: 50,
    capacity: 13200,
    power: 'Diesel',
    width: 102,
    weight: 29000,
    dailyRate: null,
    weeklyRate: null,
    monthlyRate: null,
    imageUrl: 'https://www.allaccessservices.com/fckimages/pages/equipment-rentals/telehandler_edited.jpg',
    specSheet: 'https://www.allaccessservices.com/fckimages/pdf/JLG-R1385-Rotating-Telehandler-Spec-Sheet.pdf',
  },
  {
    id: 'jlg-r11100',
    category: 'telehandlers',
    name: 'JLG R11100',
    height: 60,
    reach: 45,
    capacity: 11000,
    power: 'Diesel',
    width: 102,
    weight: 27000,
    dailyRate: null,
    weeklyRate: null,
    monthlyRate: null,
    imageUrl: 'https://www.allaccessservices.com/fckimages/pages/equipment-rentals/telehandler_edited.jpg',
    specSheet: 'https://www.allaccessservices.com/fckimages/pdf/JLG-R1385-Rotating-Telehandler-Spec-Sheet.pdf',
  },
  {
    id: 'jlg-2733',
    category: 'telehandlers',
    name: 'JLG 2733',
    height: 33,
    reach: 33,
    capacity: 26600,
    power: 'Diesel',
    width: 120,
    weight: 38000,
    dailyRate: null,
    weeklyRate: null,
    monthlyRate: null,
    imageUrl: 'https://www.allaccessservices.com/fckimages/pages/equipment-rentals/telehandler_edited.jpg',
    specSheet: 'https://www.allaccessservices.com/fckimages/pdf/2733_Specification_Sheet.pdf',
  },

  // FORKLIFTS
  {
    id: 'hyster-s50a',
    category: 'forklifts',
    name: 'Hyster S50A',
    height: 0,
    reach: 0,
    capacity: 5000,
    power: 'Propane',
    width: 42,
    weight: 9000,
    dailyRate: null,
    weeklyRate: null,
    monthlyRate: null,
    imageUrl: 'https://www.allaccessservices.com/fckimages/pages/equipment-rentals/catt.jpg',
    specSheet: 'https://www.allaccessservices.com/resources/',
  },
  {
    id: 'hyster-h80ft',
    category: 'forklifts',
    name: 'Hyster H80FT',
    height: 0,
    reach: 0,
    capacity: 8000,
    power: 'Propane',
    width: 48,
    weight: 12000,
    dailyRate: null,
    weeklyRate: null,
    monthlyRate: null,
    imageUrl: 'https://www.allaccessservices.com/fckimages/pages/equipment-rentals/catt.jpg',
    specSheet: 'https://www.allaccessservices.com/resources/',
  },
  {
    id: 'hyster-h120ft',
    category: 'forklifts',
    name: 'Hyster H120FT',
    height: 0,
    reach: 0,
    capacity: 12000,
    power: 'Propane',
    width: 54,
    weight: 16000,
    dailyRate: null,
    weeklyRate: null,
    monthlyRate: null,
    imageUrl: 'https://www.allaccessservices.com/fckimages/pages/equipment-rentals/catt.jpg',
    specSheet: 'https://www.allaccessservices.com/resources/',
  },
  {
    id: 'cat-gp25n',
    category: 'forklifts',
    name: 'Caterpillar GP25N',
    height: 0,
    reach: 0,
    capacity: 5000,
    power: 'Propane',
    width: 48,
    weight: 4200,
    dailyRate: null,
    weeklyRate: null,
    monthlyRate: null,
    imageUrl: 'https://www.allaccessservices.com/fckimages/pages/equipment-rentals/catt.jpg',
    specSheet: 'https://www.allaccessservices.com/fckimages/pdf/Caterpillar-GP25N-spetsifikatsioon.pdf',
  },
];

export const rentalCategories = [
  {
    slug: 'scissor-lifts',
    name: 'Scissor Lifts',
    image: 'https://media.base44.com/images/public/69e03c311db29c3c17ba7e75/b8572ae2b_scissor-lift.png',
    accentColor: '#f97316',
    heightRange: '13–53 ft',
    description: 'Electric & rough terrain platforms. Ideal for flat surfaces and indoor jobs.',
  },
  {
    slug: 'telehandlers',
    name: 'Telehandlers',
    image: 'https://media.base44.com/images/public/69e03c311db29c3c17ba7e75/8f9a3cf95_telehandler.png',
    accentColor: '#eab308',
    heightRange: '5,000–36,000 lb',
    description: 'Telescopic material handlers from compact to heavy-lift configurations.',
  },
  {
    slug: 'forklifts',
    name: 'Forklifts',
    image: 'https://media.base44.com/images/public/69e03c311db29c3c17ba7e75/68ec6d6b6_front-forklifts-diesel-d120s-7-doosan.jpg',
    images: [
      'https://media.base44.com/images/public/69e03c311db29c3c17ba7e75/68ec6d6b6_front-forklifts-diesel-d120s-7-doosan.jpg',
      'https://media.base44.com/images/public/69e03c311db29c3c17ba7e75/fa8fe351f_Class-V-Truck-for-Flyer-.png'
    ],
    accentColor: '#22c55e',
    heightRange: '3,000–27,000 lb',
    description: 'Propane-powered forklifts for warehouse and outdoor yard use.',
  },
  {
    slug: 'straight-boom-lifts',
    name: 'Straight Boom Lifts',
    image: 'https://media.base44.com/images/public/69e03c311db29c3c17ba7e75/35db815b4_600S-HC3-Gallery.jpg',
    accentColor: '#3b82f6',
    heightRange: '40–185 ft',
    description: 'Straight boom lifts for reaching over obstacles and high structures.',
  },
  {
    slug: 'articulating-boom-lifts',
    name: 'Articulating Boom Lifts',
    image: 'https://media.base44.com/images/public/69e03c311db29c3c17ba7e75/d691b3fe6_boom-lift.png',
    accentColor: '#8b5cf6',
    heightRange: '30–100 ft',
    description: 'Knuckle boom, articulating, and crawler lifts for maximum maneuverability.',
  },
  {
    slug: 'specialty-lifts',
    name: 'Specialty Lifts & Attachments',
    image: 'https://media.base44.com/images/public/69e03c311db29c3c17ba7e75/d691b3fe6_boom-lift.png',
    accentColor: '#ec4899',
    heightRange: 'Various',
    description: 'Specialized equipment and attachment solutions for unique projects.',
  },
];

export const powerSources = ['Electric', 'Diesel', 'Propane'];
export const heightRanges = [
  { label: 'Under 20 ft', min: 0, max: 20 },
  { label: '20-40 ft', min: 20, max: 40 },
  { label: '40-60 ft', min: 40, max: 60 },
  { label: '60-100 ft', min: 60, max: 100 },
  { label: '100+ ft', min: 100, max: 200 },
];
export const widthRanges = [
  { label: 'Compact (under 50 in)', min: 0, max: 50 },
  { label: 'Standard (50-96 in)', min: 50, max: 96 },
  { label: 'Wide (96+ in)', min: 96, max: 120 },
];